import { drizzleFkViolation } from '@borradh-workspace/database';
import {
  beforeEach,
  createMockDatabase,
  describe,
  expect,
  expectResult,
  it,
  vi,
} from '@borradh-workspace/testing';
import { ErrorCodes } from '../../../shared/index.js';
import {
  linkAssetServices,
  unlinkAssetServices,
} from './link-asset-services.service.js';

describe('linkAssetServices', () => {
  const mockDb = createMockDatabase();

  beforeEach(() => {
    vi.clearAllMocks();
    mockDb._resetMocks();
  });

  const validInput = {
    assetId: 'asset_123',
    organizationId: 'org_123',
    serviceIds: ['svc_1', 'svc_2'],
    isManual: true,
  };

  it('should link services to asset successfully', async () => {
    const mockAsset = {
      id: 'asset_123',
      name: 'Test Video',
      organizationId: 'org_123',
    };

    const mockServices = [
      { id: 'svc_1', name: 'Haircut', organizationId: 'org_123' },
      { id: 'svc_2', name: 'Coloring', organizationId: 'org_123' },
    ];

    const mockLinks = [
      {
        id: 'link_1',
        assetId: 'asset_123',
        serviceId: 'svc_1',
        isAutoGenerated: false,
      },
      {
        id: 'link_2',
        assetId: 'asset_123',
        serviceId: 'svc_2',
        isAutoGenerated: false,
      },
    ];

    // Step 1: verify asset exists
    mockDb.query.asset.findFirst.mockResolvedValueOnce(mockAsset);
    // Step 2: verify services exist
    mockDb.query.organizationService.findMany.mockResolvedValueOnce(
      mockServices
    );
    // Step 3: insert links
    mockDb.returning.mockResolvedValueOnce(mockLinks);

    const result = await linkAssetServices(mockDb as never, validInput);

    expect(result.success).toBe(true);
    if (result.success) {
      expect(result.data).toHaveLength(2);
      expect(result.data[0].serviceId).toBe('svc_1');
      expect(result.data[1].serviceId).toBe('svc_2');
    }

    expect(mockDb.insert).toHaveBeenCalled();
  });

  it('should return NOT_FOUND when asset not found', async () => {
    mockDb.query.asset.findFirst.mockResolvedValueOnce(null);

    await expectResult(
      linkAssetServices(mockDb as never, validInput)
    ).toFailWithCode(ErrorCodes.NOT_FOUND);

    expect(mockDb.insert).not.toHaveBeenCalled();
  });

  it('should return NOT_FOUND when some services not found', async () => {
    const mockAsset = {
      id: 'asset_123',
      name: 'Test Video',
      organizationId: 'org_123',
    };

    // Only one service found out of two requested
    const mockServices = [
      { id: 'svc_1', name: 'Haircut', organizationId: 'org_123' },
    ];

    mockDb.query.asset.findFirst.mockResolvedValueOnce(mockAsset);
    mockDb.query.organizationService.findMany.mockResolvedValueOnce(
      mockServices
    );

    const result = await linkAssetServices(mockDb as never, validInput);

    expect(result.success).toBe(false);
    if (!result.success) {
      expect(result.error.code).toBe(ErrorCodes.NOT_FOUND);
      expect(result.error.message).toContain('Some services not found');
    }

    expect(mockDb.insert).not.toHaveBeenCalled();
  });

  it('should return NOT_FOUND when the asset is deleted between the check and the insert (race)', async () => {
    const mockAsset = {
      id: 'asset_123',
      name: 'Test Video',
      organizationId: 'org_123',
    };
    const mockServices = [
      { id: 'svc_1', name: 'Haircut', organizationId: 'org_123' },
      { id: 'svc_2', name: 'Coloring', organizationId: 'org_123' },
    ];

    mockDb.query.asset.findFirst.mockResolvedValueOnce(mockAsset);
    mockDb.query.organizationService.findMany.mockResolvedValueOnce(
      mockServices
    );
    mockDb.returning.mockRejectedValueOnce(
      drizzleFkViolation('asset_service_asset_id_asset_id_fk')
    );

    await expectResult(
      linkAssetServices(mockDb as never, validInput)
    ).toFailWithCode(ErrorCodes.NOT_FOUND);
  });

  it('should return VALIDATION_ERROR for empty serviceIds', async () => {
    const invalidInput = {
      ...validInput,
      serviceIds: [],
    };

    await expectResult(
      linkAssetServices(mockDb as never, invalidInput)
    ).toFailWithCode(ErrorCodes.VALIDATION_ERROR);

    expect(mockDb.query.asset.findFirst).not.toHaveBeenCalled();
  });

  it('should return VALIDATION_ERROR for empty assetId', async () => {
    const invalidInput = {
      ...validInput,
      assetId: '',
    };

    await expectResult(
      linkAssetServices(mockDb as never, invalidInput)
    ).toFailWithCode(ErrorCodes.VALIDATION_ERROR);

    expect(mockDb.query.asset.findFirst).not.toHaveBeenCalled();
  });

  it('should return VALIDATION_ERROR for empty organizationId', async () => {
    const invalidInput = {
      ...validInput,
      organizationId: '',
    };

    await expectResult(
      linkAssetServices(mockDb as never, invalidInput)
    ).toFailWithCode(ErrorCodes.VALIDATION_ERROR);

    expect(mockDb.query.asset.findFirst).not.toHaveBeenCalled();
  });
});

describe('unlinkAssetServices', () => {
  const mockDb = createMockDatabase();

  beforeEach(() => {
    vi.clearAllMocks();
    mockDb._resetMocks();
  });

  const validInput = {
    assetId: 'asset_123',
    organizationId: 'org_123',
    serviceIds: ['svc_1', 'svc_2'],
  };

  it('should unlink services successfully', async () => {
    const mockAsset = {
      id: 'asset_123',
      name: 'Test Video',
      organizationId: 'org_123',
    };

    const deletedLinks = [
      { id: 'link_1', assetId: 'asset_123', serviceId: 'svc_1' },
      { id: 'link_2', assetId: 'asset_123', serviceId: 'svc_2' },
    ];

    // Step 1: verify asset exists
    mockDb.query.asset.findFirst.mockResolvedValueOnce(mockAsset);
    // Step 2: delete links
    mockDb.returning.mockResolvedValueOnce(deletedLinks);

    const result = await unlinkAssetServices(mockDb as never, validInput);

    expect(result.success).toBe(true);
    if (result.success) {
      expect(result.data.deletedCount).toBe(2);
    }

    expect(mockDb.delete).toHaveBeenCalled();
  });

  it('should return NOT_FOUND when asset not found', async () => {
    mockDb.query.asset.findFirst.mockResolvedValueOnce(null);

    await expectResult(
      unlinkAssetServices(mockDb as never, validInput)
    ).toFailWithCode(ErrorCodes.NOT_FOUND);

    expect(mockDb.delete).not.toHaveBeenCalled();
  });

  it('should return VALIDATION_ERROR for empty serviceIds', async () => {
    const invalidInput = {
      ...validInput,
      serviceIds: [],
    };

    await expectResult(
      unlinkAssetServices(mockDb as never, invalidInput)
    ).toFailWithCode(ErrorCodes.VALIDATION_ERROR);

    expect(mockDb.query.asset.findFirst).not.toHaveBeenCalled();
  });

  it('should return VALIDATION_ERROR for empty assetId', async () => {
    const invalidInput = {
      ...validInput,
      assetId: '',
    };

    await expectResult(
      unlinkAssetServices(mockDb as never, invalidInput)
    ).toFailWithCode(ErrorCodes.VALIDATION_ERROR);

    expect(mockDb.query.asset.findFirst).not.toHaveBeenCalled();
  });

  it('should handle zero deleted links', async () => {
    const mockAsset = {
      id: 'asset_123',
      name: 'Test Video',
      organizationId: 'org_123',
    };

    mockDb.query.asset.findFirst.mockResolvedValueOnce(mockAsset);
    mockDb.returning.mockResolvedValueOnce([]);

    const result = await unlinkAssetServices(mockDb as never, validInput);

    expect(result.success).toBe(true);
    if (result.success) {
      expect(result.data.deletedCount).toBe(0);
    }
  });
});
