import { z } from 'zod';

/**
 * Link asset services input schema
 */
export const linkAssetServicesSchema = z.object({
  assetId: z.string().min(1, 'Asset ID is required'),
  organizationId: z.string().min(1, 'Organization ID is required'),
  /** Service IDs to link to this asset */
  serviceIds: z
    .array(z.string().min(1))
    .min(1, 'At least one service ID is required'),
  /** Whether this is a manual link (not auto-generated by AI) */
  isManual: z.boolean().optional().default(true),
});

export type LinkAssetServicesInput = z.infer<typeof linkAssetServicesSchema>;

/**
 * Unlink asset services input schema
 */
export const unlinkAssetServicesSchema = z.object({
  assetId: z.string().min(1, 'Asset ID is required'),
  organizationId: z.string().min(1, 'Organization ID is required'),
  /** Service IDs to unlink from this asset */
  serviceIds: z
    .array(z.string().min(1))
    .min(1, 'At least one service ID is required'),
});

export type UnlinkAssetServicesInput = z.infer<
  typeof unlinkAssetServicesSchema
>;
