import {
  asset,
  assetService,
  isForeignKeyViolation,
  withOrgScope,
} from '@borradh-workspace/database';
import { trackedResult } from '@borradh-workspace/observability';
import { and, eq, inArray } from 'drizzle-orm';
import {
  type DbConnection,
  ErrorCodes,
  FeatureError,
  type Result,
  err,
  notDeleted,
  ok,
} from '../../../shared/index.js';
import {
  type LinkAssetServicesInput,
  type UnlinkAssetServicesInput,
  linkAssetServicesSchema,
  unlinkAssetServicesSchema,
} from './link-asset-services.schema.js';

/**
 * Internal implementation of link asset services
 */
const linkAssetServicesImpl = async (
  db: DbConnection,
  input: LinkAssetServicesInput
): Promise<Result<(typeof assetService.$inferSelect)[]>> => {
  // Validate input
  const parsed = linkAssetServicesSchema.safeParse(input);
  if (!parsed.success) {
    return err(
      new FeatureError(ErrorCodes.VALIDATION_ERROR, 'Invalid input', {
        issues: parsed.error.issues,
      })
    );
  }

  const { assetId, organizationId, serviceIds, isManual } = parsed.data;

  return withOrgScope(
    async (tx) => {
      // Verify asset exists and belongs to the organization
      const existingAsset = await tx.query.asset.findFirst({
        where: and(
          eq(asset.id, assetId),
          eq(asset.organizationId, organizationId),
          notDeleted(asset)
        ),
      });

      if (!existingAsset) {
        return err(
          new FeatureError(ErrorCodes.NOT_FOUND, 'Asset not found', { assetId })
        );
      }

      // Verify all services exist and belong to the organization
      const existingServices = await tx.query.organizationService.findMany({
        where: (s, { and, eq, inArray }) =>
          and(eq(s.organizationId, organizationId), inArray(s.id, serviceIds)),
      });

      if (existingServices.length !== serviceIds.length) {
        const foundIds = new Set(existingServices.map((s) => s.id));
        const missingIds = serviceIds.filter((id) => !foundIds.has(id));
        return err(
          new FeatureError(ErrorCodes.NOT_FOUND, 'Some services not found', {
            missingIds,
          })
        );
      }

      // Create links (ignore conflicts for existing links)
      const links: (typeof assetService.$inferInsert)[] = serviceIds.map(
        (serviceId) => ({
          assetId,
          serviceId,
          isAutoGenerated: !isManual,
        })
      );

      // Use upsert to handle duplicates
      try {
        const results = await tx
          .insert(assetService)
          .values(links)
          .onConflictDoNothing({
            target: [assetService.assetId, assetService.serviceId],
          })
          .returning();

        return ok(results);
      } catch (error) {
        // The asset was deleted between the existence check above and this
        // insert (a genuine race, not a bug in the check). drizzle wraps the
        // postgres.js error — the constraint lives on the `.cause` chain, not
        // `error.message` (see isForeignKeyViolation).
        if (
          isForeignKeyViolation(error, 'asset_service_asset_id_asset_id_fk')
        ) {
          return err(
            new FeatureError(ErrorCodes.NOT_FOUND, 'Asset not found', {
              assetId,
            })
          );
        }
        throw error;
      }
    },
    { db }
  );
};

/**
 * Link services to an asset (manual linking)
 *
 * @param db - Database connection
 * @param input - Link asset services input
 * @returns Result with created links or error
 */
export const linkAssetServices = (
  db: DbConnection,
  input: LinkAssetServicesInput
) =>
  trackedResult(
    'assets.linkAssetServices',
    () => linkAssetServicesImpl(db, input),
    {
      properties: {
        assetId: input.assetId,
        organizationId: input.organizationId,
        serviceCount: input.serviceIds.length,
      },
    }
  );

/**
 * Result type for linkAssetServices
 */
export type LinkAssetServicesResult = Awaited<
  ReturnType<typeof linkAssetServices>
>;

/**
 * Internal implementation of unlink asset services
 */
const unlinkAssetServicesImpl = async (
  db: DbConnection,
  input: UnlinkAssetServicesInput
): Promise<Result<{ deletedCount: number }>> => {
  // Validate input
  const parsed = unlinkAssetServicesSchema.safeParse(input);
  if (!parsed.success) {
    return err(
      new FeatureError(ErrorCodes.VALIDATION_ERROR, 'Invalid input', {
        issues: parsed.error.issues,
      })
    );
  }

  const { assetId, organizationId, serviceIds } = parsed.data;

  return withOrgScope(
    async (tx) => {
      // Verify asset exists and belongs to the organization
      const existingAsset = await tx.query.asset.findFirst({
        where: and(
          eq(asset.id, assetId),
          eq(asset.organizationId, organizationId),
          notDeleted(asset)
        ),
      });

      if (!existingAsset) {
        return err(
          new FeatureError(ErrorCodes.NOT_FOUND, 'Asset not found', { assetId })
        );
      }

      // Delete the links
      const result = await tx
        .delete(assetService)
        .where(
          and(
            eq(assetService.assetId, assetId),
            inArray(assetService.serviceId, serviceIds)
          )
        )
        .returning();

      return ok({ deletedCount: result.length });
    },
    { db }
  );
};

/**
 * Unlink services from an asset
 *
 * @param db - Database connection
 * @param input - Unlink asset services input
 * @returns Result with deleted count or error
 */
export const unlinkAssetServices = (
  db: DbConnection,
  input: UnlinkAssetServicesInput
) =>
  trackedResult(
    'assets.unlinkAssetServices',
    () => unlinkAssetServicesImpl(db, input),
    {
      properties: {
        assetId: input.assetId,
        organizationId: input.organizationId,
        serviceCount: input.serviceIds.length,
      },
    }
  );

/**
 * Result type for unlinkAssetServices
 */
export type UnlinkAssetServicesResult = Awaited<
  ReturnType<typeof unlinkAssetServices>
>;
