import type { VideoDraftConfig } from '@borradh-workspace/database';
import { describe, expect, it } from '@borradh-workspace/testing';
import { templateDocSchema } from '@borradh-workspace/video-templates';

import { convertAuthorityTts } from './convert-authority-tts.service.js';

// Representative v1 authority-2 / -3 draftConfig fixture. AI-voiceover
// authority videos carried: scriptText (regenerated by v2, not used here),
// narrationType: 'ai_voiceover', an aiVoiceId, b-roll clips, music settings,
// and an outro card. No talkingHeadAssetId on this shape.
function fixtureDraftConfig(): VideoDraftConfig {
  return {
    scriptText:
      'At Cosmetic Clinic, teeth whitening is used to help improve discolouration, staining, and dullness. By up to 80 percentage. The clinic has helped 250+ clients across London.',
    narrationType: 'ai_voiceover',
    aiVoiceId: 'kokoro-en-female-1',
    talkingHeadAssetId: null,
    talkingHeadUrl: null,
    bRollClips: [
      { assetId: 'asset-procedure-1', order: 1, clipType: 'bRoll' },
      { assetId: 'asset-environment-1', order: 2, clipType: 'bRoll' },
      { assetId: 'asset-procedure-2', order: 3, clipType: 'bRoll' },
    ],
    captions: {
      enabled: true,
      position: 'bottom',
      fontFamily: 'Inter',
      fontSize: 48,
      textColor: '#FFFFFF',
      highlightColor: '#FFD700',
      backgroundColor: '#000000',
      showBackground: true,
    },
    musicTrackId: 'tea-pop',
    musicUrl: 'https://cdn.example.com/audio/tea-pop.mp3',
    musicVolume: 0.35,
    outro: {
      logoUrl: 'https://cdn.example.com/logo.png',
      businessName: 'Cosmetic Clinic',
      ctaText: 'Book a consultation',
      backgroundOpacity: 0.9,
      backgroundColor: '#0066FF',
      textColor: '#FFFFFF',
      durationSec: 3,
    },
    orientation: 'portrait',
  };
}

describe('convertAuthorityTts', () => {
  describe('authority-2', () => {
    it('returns templateId === "authority-2"', () => {
      const result = convertAuthorityTts('authority-2', fixtureDraftConfig());
      expect(result.templateId).toBe('authority-2');
    });

    it('returns a TemplateDoc that parses against templateDocSchema', () => {
      const result = convertAuthorityTts('authority-2', fixtureDraftConfig());
      const parsed = templateDocSchema.safeParse(result.templateDoc);
      if (!parsed.success) {
        throw new Error(
          `templateDocSchema rejected converted authority-2: ${JSON.stringify(
            parsed.error.issues,
            null,
            2
          )}`
        );
      }
      expect(parsed.success).toBe(true);
    });

    it('uses TTS narration (Shape B invariant)', () => {
      const result = convertAuthorityTts('authority-2', fixtureDraftConfig());
      expect(result.templateDoc.globals.audio.narration?.source).toBe('tts');
    });

    it('has captions configured from narration (Whisper)', () => {
      const result = convertAuthorityTts('authority-2', fixtureDraftConfig());
      expect(result.templateDoc.globals.audio.narration?.source).toBe('tts');
      expect(result.templateDoc.globals.captions?.from).toBe('narration');
    });

    it('does not have a talking-head spine block', () => {
      const result = convertAuthorityTts('authority-2', fixtureDraftConfig());
      // Shape B: b-roll only, no talking-head clip on the spine.
      expect(result.templateDoc.root.kind).toBe('leaf');
      if (result.templateDoc.root.kind !== 'leaf') return;
      // The one spine block is the b-roll media-track — its query tag should
      // NOT be the talking-head tag (authority-1 / Shape A uses
      // 'employee-talking-head'; Shape B uses 'procedure').
      const spine = result.templateDoc.root.spine[0];
      expect(spine?.kind).toBe('media-track');
      if (!spine || spine.kind !== 'media-track') return;
      expect(spine.clips.source).toBe('query');
      if (spine.clips.source !== 'query') return;
      if (spine.clips.query.kind === 'asset-clips') {
        expect(spine.clips.query.tag).not.toBe('employee-talking-head');
      }
    });
  });

  describe('authority-3', () => {
    it('returns templateId === "authority-3"', () => {
      const result = convertAuthorityTts('authority-3', fixtureDraftConfig());
      expect(result.templateId).toBe('authority-3');
    });

    it('returns a TemplateDoc that parses against templateDocSchema', () => {
      const result = convertAuthorityTts('authority-3', fixtureDraftConfig());
      const parsed = templateDocSchema.safeParse(result.templateDoc);
      if (!parsed.success) {
        throw new Error(
          `templateDocSchema rejected converted authority-3: ${JSON.stringify(
            parsed.error.issues,
            null,
            2
          )}`
        );
      }
      expect(parsed.success).toBe(true);
    });

    it('uses TTS narration (Shape B invariant)', () => {
      const result = convertAuthorityTts('authority-3', fixtureDraftConfig());
      expect(result.templateDoc.globals.audio.narration?.source).toBe('tts');
    });
  });

  describe('brandFieldsForTheme extraction', () => {
    it('extracts primary colour from outro.backgroundColor', () => {
      const result = convertAuthorityTts('authority-2', fixtureDraftConfig());
      expect(result.brandFieldsForTheme.colors?.primary).toBe('#0066FF');
    });

    it('extracts onPrimary colour from outro.textColor', () => {
      const result = convertAuthorityTts('authority-2', fixtureDraftConfig());
      expect(result.brandFieldsForTheme.colors?.onPrimary).toBe('#FFFFFF');
    });

    it('extracts logo URL from outro.logoUrl as the light variant', () => {
      const result = convertAuthorityTts('authority-2', fixtureDraftConfig());
      expect(result.brandFieldsForTheme.logo?.light).toBe(
        'https://cdn.example.com/logo.png'
      );
    });

    it('extracts business name and CTA text into identity', () => {
      const result = convertAuthorityTts('authority-2', fixtureDraftConfig());
      expect(result.brandFieldsForTheme.identity?.businessName).toBe(
        'Cosmetic Clinic'
      );
      expect(result.brandFieldsForTheme.identity?.ctaText).toBe(
        'Book a consultation'
      );
    });

    it('skips brand fields when v1 outro values are missing', () => {
      const config: VideoDraftConfig = {
        ...fixtureDraftConfig(),
        outro: {
          businessName: '',
          ctaText: '',
          backgroundOpacity: 0.9,
          backgroundColor: 'not-a-color',
          textColor: '',
          durationSec: 3,
        },
      };
      const result = convertAuthorityTts('authority-2', config);
      expect(result.brandFieldsForTheme.colors).toBeUndefined();
      expect(result.brandFieldsForTheme.identity).toBeUndefined();
      expect(result.brandFieldsForTheme.logo).toBeUndefined();
    });
  });

  describe('themeOverridesForVideo extraction', () => {
    it('lifts aiVoiceId into themeOverridesForVideo.narrationVoice', () => {
      const result = convertAuthorityTts('authority-2', fixtureDraftConfig());
      expect(result.themeOverridesForVideo?.narrationVoice).toBe(
        'kokoro-en-female-1'
      );
    });

    it('lifts musicTrackId into themeOverridesForVideo.musicTrackId', () => {
      const result = convertAuthorityTts('authority-2', fixtureDraftConfig());
      expect(result.themeOverridesForVideo?.musicTrackId).toBe('tea-pop');
    });

    it('lifts musicVolume into themeOverridesForVideo.musicVolume', () => {
      const result = convertAuthorityTts('authority-2', fixtureDraftConfig());
      expect(result.themeOverridesForVideo?.musicVolume).toBe(0.35);
    });

    it('omits themeOverridesForVideo when no v1 overrides were set', () => {
      const config: VideoDraftConfig = {
        ...fixtureDraftConfig(),
        aiVoiceId: null,
        musicTrackId: undefined,
        // musicVolume is required on VideoDraftConfig; leave it set but
        // verify the converter handles a 0-valued / unset combination via
        // the next dedicated test.
      };
      // musicVolume is still present here; we test the *both-absent* path
      // by removing all override-eligible fields explicitly.
      const result = convertAuthorityTts('authority-2', config);
      // narrationVoice is gone, but musicVolume is still a number → side
      // channel is present and carries musicVolume only. That's intentional.
      expect(result.themeOverridesForVideo?.narrationVoice).toBeUndefined();
      expect(result.themeOverridesForVideo?.musicTrackId).toBeUndefined();
      expect(result.themeOverridesForVideo?.musicVolume).toBe(
        config.musicVolume
      );
    });
  });
});
