/**
 * AI Recommendations Types
 *
 * Types and constants for the recommendations feature.
 * These are computed at runtime, not stored in the database.
 */

// =============================================================================
// RECOMMENDATION TYPE
// =============================================================================

export const recommendationTypeLabels = {
  scale: 'Scale Opportunity',
  learning: 'Learning Phase',
  burnout: 'Ad Burnout',
  high_cpl: 'High Cost Per Lead',
  turn_off: 'Turn Off Ad',
  performing_well: 'Performing Well',
} as const;

export const recommendationTypeValues = Object.keys(
  recommendationTypeLabels
) as (keyof typeof recommendationTypeLabels)[];

export type RecommendationType = keyof typeof recommendationTypeLabels;

// =============================================================================
// RECOMMENDATION PRIORITY
// =============================================================================

export const recommendationPriorityLabels = {
  critical: 'Critical',
  high: 'High',
  medium: 'Medium',
  low: 'Low',
} as const;

export const recommendationPriorityValues = Object.keys(
  recommendationPriorityLabels
) as (keyof typeof recommendationPriorityLabels)[];

export type RecommendationPriority = keyof typeof recommendationPriorityLabels;

/**
 * Priority order for sorting (lower number = higher priority)
 */
export const PRIORITY_ORDER: Record<RecommendationPriority, number> = {
  critical: 0,
  high: 1,
  medium: 2,
  low: 3,
};

// =============================================================================
// CPL RATING
// =============================================================================

export const cplRatingLabels = {
  excellent: 'Excellent',
  good: 'Good',
  acceptable: 'Acceptable',
  concerning: 'Concerning',
  poor: 'Poor',
} as const;

export const cplRatingValues = Object.keys(
  cplRatingLabels
) as (keyof typeof cplRatingLabels)[];

export type CplRating = keyof typeof cplRatingLabels;

// =============================================================================
// THRESHOLDS (Without SMS verification)
// =============================================================================

/**
 * CPL Thresholds in EUR
 *
 * | Rating     | CPL      | Recommendation             |
 * |------------|----------|----------------------------|
 * | Excellent  | <= €5    | Scale opportunity          |
 * | Good       | <= €8    | Performing well            |
 * | Acceptable | <= €15   | No recommendation          |
 * | Concerning | <= €20   | Review creative            |
 * | Poor       | > €20    | Turn off ad                |
 */
export const CPL_THRESHOLDS = {
  EXCELLENT: 5,
  GOOD: 8,
  ACCEPTABLE: 15,
  CONCERNING: 20,
} as const;

/**
 * Learning phase threshold in EUR
 * Ads with total spend < €75 are considered "learning"
 */
export const LEARNING_PHASE_THRESHOLD = 75;

/**
 * Burnout detection thresholds
 */
export const BURNOUT_THRESHOLDS = {
  /** Frequency threshold for critical burnout */
  CRITICAL_FREQUENCY: 3.0,
  /** Frequency threshold for warning burnout */
  WARNING_FREQUENCY: 2.5,
  /** Number of consecutive days of rising CPL to detect burnout */
  RISING_CPL_DAYS: 4,
  /** CTR decline percentage to trigger warning (20%) */
  CTR_DECLINE_THRESHOLD: 0.2,
} as const;

// =============================================================================
// INTERFACES
// =============================================================================

/**
 * Daily insight data from Meta API
 */
export interface DailyInsight {
  date: string;
  spend: number;
  impressions: number;
  clicks: number;
  leads: number;
  cpl: number | null;
  ctr: number;
  frequency: number;
}

/**
 * Analysis data for an ad
 */
export interface AdAnalysis {
  adId: string;
  adName: string;
  campaignId: string;
  campaignName: string;
  totalSpend: number;
  totalLeads: number;
  averageCpl: number | null;
  currentFrequency: number;
  dailyInsights: DailyInsight[];
  isLearning: boolean;
  cplRating: CplRating | null;
}

/**
 * A recommendation generated by the system
 */
export interface Recommendation {
  id: string;
  type: RecommendationType;
  priority: RecommendationPriority;
  title: string;
  description: string;
  adId: string;
  adName: string;
  campaignId: string;
  campaignName: string;
  metrics: {
    cpl?: number | null;
    spend?: number;
    leads?: number;
    frequency?: number;
    ctr?: number;
  };
  createdAt: string;
}

/**
 * Response from get-recommendations service
 */
export interface RecommendationsResult {
  recommendations: Recommendation[];
  analyzedAdsCount: number;
  hasMetaIntegration: boolean;
}
