export {
  CONTENT_IDEA_TEMPLATES,
  DEFAULT_MAX_BROLL_CLIPS,
  ORGANIC_TEMPLATE_IDS,
  RETIRED_TEMPLATE_IDS,
  SHARED_MUSIC_TRACKS,
  getOrganicTemplates,
  getPlannableOrganicTemplates,
  getSelectableTemplates,
  getTemplateById,
  getRandomVariation,
  getVariationById,
  isRetiredTemplate,
  selectRandomVariationForTemplate,
  type ContentIdeaTemplate,
  type OrganicTemplateId,
  type TemplateMusicTrack,
  type TemplateVariation,
  type TemplateClipGuidance,
  type TemplateRenderingConfig,
} from './template-definitions.js';
