import {
  aspectRatioValues,
  graphicStatusLabels,
  graphicStatusValues,
  graphicUsageTypeValues,
} from '@borradh-workspace/labels';
import { relations } from 'drizzle-orm';
import {
  boolean,
  index,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  text,
  timestamp,
} from 'drizzle-orm/pg-core';
import { orgRlsPolicy } from '../rls-policy.js';
import { organizationService } from './organization-service.js';
import { organization } from './organization.js';
import { user } from './user.js';

// Re-export labels and types for consumers
export { graphicStatusLabels, graphicStatusValues };
export type {
  GraphicStatus,
  GraphicUsageType,
  AspectRatio,
} from '@borradh-workspace/labels';

// Database enums — shared with image-template.ts via the labels package.
export const graphicStatusEnum = pgEnum('graphic_status', graphicStatusValues);
export const graphicUsageTypeEnum = pgEnum(
  'graphic_usage_type',
  graphicUsageTypeValues
);
export const aspectRatioEnum = pgEnum('aspect_ratio', aspectRatioValues);

/**
 * Rendered output for a specific aspect ratio. One per platform export the
 * worker produced. The renderer writes these as it finishes each slide.
 */
export interface GraphicOutput {
  aspectRatioId: string;
  platform: string;
  width: number;
  height: number;
  url: string;
  format: 'png' | 'jpg' | 'webp';
  renderedAt: string;
  /** Low-res thumbnail URL for fast grid/list previews (full-res `url` for detail). */
  thumbnailUrl?: string;
  /** Which slide this output is for (carousel support) */
  slideId?: string;
  /** Slide order for sorting */
  slideOrder?: number;
  /** S3 object key for the rendered asset (persisted so we can re-sign URLs) */
  objectKey?: string;
  /** Which path produced this output — 'client' (browser) or 'server' (worker) */
  renderedBy?: 'client' | 'server';
  /** Outcome for this particular slide. Absent = 'success' for back-compat. */
  status?: 'success' | 'failed';
  /** When `status === 'failed'`, a short diagnostic string. */
  error?: string;
}

/**
 * Graphic table — a user-facing graphic generated by the branded-graphic
 * (nano-banana / Gemini) engine from the org's real service media + brand
 * corpus.
 *
 * `serviceId` + `topicSummary` + `kind` capture what the graphic was
 * generated from so it can be re-rolled (regenerate) without any stored
 * template/slot-fill state.
 */
export const graphic = pgTable(
  'graphic',
  {
    id: text('id').primaryKey(),
    title: text('title'),

    // Render-pipeline status (draft → rendering → ready / failed).
    status: graphicStatusEnum('status').notNull().default('draft'),

    // Whether this graphic is intended for paid ads or organic social posts.
    // Drives where it surfaces (Ads inbox vs Socials) and which monthly
    // batches pick it up.
    usageType: graphicUsageTypeEnum('usage_type').notNull().default('ad'),

    // What the graphic was generated from — the source the nano-banana engine
    // renders from, and what `regenerate` re-rolls. `serviceId` is nullable so
    // deleting a service doesn't cascade-delete its graphics.
    serviceId: text('service_id').references(() => organizationService.id, {
      onDelete: 'set null',
    }),
    topicSummary: text('topic_summary'),
    kind: text('kind')
      .$type<'single' | 'carousel'>()
      .notNull()
      .default('single'),

    // The curated template slug the nano-banana engine rendered this graphic
    // with. Persisted so a regenerate re-rolls against the SAME template
    // instead of re-hashing a fresh graphicId into a different one (which made
    // "tweak this slide" swap the whole design). Null for legacy rows / the
    // Fabric path.
    templateSlug: text('template_slug'),

    /**
     * The exact copy text rendered onto this graphic.
     *
     * Persisted so a REGENERATE can amend it instead of inventing a new deck.
     * Copy is written fresh by an LLM on every render, and nothing used to
     * survive the render — so "change the headline" produced a brand-new
     * headline AND brand-new body, CTA and everything else, because there was
     * no previous text to hold onto. Storing it lets the next render be told
     * "here is the current copy, change ONLY what was asked".
     */
    renderedCopy: text('rendered_copy'),

    // Generation provenance. These inputs are intentionally persisted so a
    // later regeneration uses the same paid/organic context and the owner's
    // explicitly selected source imagery instead of silently falling back to
    // an organic, auto-selected render.
    offerId: text('offer_id'),
    sourceAssetIds: text('source_asset_ids').array(),
    allowAiImages: boolean('allow_ai_images'),

    // Canvas dimensions (shared across all slides).
    aspectRatio: aspectRatioEnum('aspect_ratio').default('4:5'),
    canvasWidth: integer('canvas_width').default(1080),
    canvasHeight: integer('canvas_height').default(1350),

    // Rendered outputs (array of GraphicOutput per aspect ratio/slide).
    outputs: jsonb('outputs').$type<GraphicOutput[]>(),

    // Stable support code + safe user-facing message for terminal generation
    // failures. Internal provider details remain in structured worker logs.
    errorCode: text('error_code'),
    errorMessage: text('error_message'),

    // Ownership
    organizationId: text('organization_id')
      .notNull()
      .references(() => organization.id, { onDelete: 'cascade' }),
    createdById: text('created_by_id').references(() => user.id, {
      onDelete: 'set null',
    }),

    // Timestamps
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at')
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (table) => [
    index('idx_graphic_org_id').on(table.organizationId),
    index('idx_graphic_service_id').on(table.serviceId),
    index('idx_graphic_created_by_id').on(table.createdById),
    index('idx_graphic_org_usage_type').on(
      table.organizationId,
      table.usageType
    ),
  ]
);

export const graphicRlsPolicy = orgRlsPolicy(graphic);

export const graphicRelations = relations(graphic, ({ one }) => ({
  organization: one(organization, {
    fields: [graphic.organizationId],
    references: [organization.id],
  }),
  createdBy: one(user, {
    fields: [graphic.createdById],
    references: [user.id],
  }),
  service: one(organizationService, {
    fields: [graphic.serviceId],
    references: [organizationService.id],
  }),
}));

export type Graphic = typeof graphic.$inferSelect;
export type NewGraphic = typeof graphic.$inferInsert;
