export {
  generateEmbedding,
  generateEmbeddings,
  queryKnowledge,
  formatKnowledgeContext,
  upsertKnowledgeEntry,
  populateOrgProfile,
  populateServices,
  populateAdInsights,
  populatePostInsights,
  populateVideoPreferences,
  populateCustomerPatterns,
  populateAll,
  addKnowledgeEntry,
  KNOWLEDGE_REFRESH_SCHEDULE,
  aggregateAdInsights,
  aggregatePostInsights,
  aggregateTargetingInsights,
  runAllAggregations,
  type KnowledgeSearchResult,
  getKnowledgeForChatbot,
  extractFAQs,
  extractChatbotInsights,
  extractAdChatbotPatterns,
  KNOWLEDGE_UPDATE_QUEUE,
  type KnowledgeUpdateType,
  type KnowledgeUpdateJobPayload,
  queueKnowledgeUpdate,
  processKnowledgeUpdateJob,
  closeKnowledgeUpdateQueue,
  getKnowledgeUpdateQueue,
} from './knowledge/index.js';

export {
  getPlanAssistantLimits,
  PLAN_ASSISTANT_LIMITS,
  type PlanAssistantLimits,
} from './models/index.js';

export {
  SKILL_REGISTRY_VERSION,
  buildToolListForSkills,
  getSkillById,
  skills,
  // Single skill registry (fewer-steps content) used for every conversation.
  skillRegistry,
  type ResolvedSkillRegistry,
  defaultSkill,
  createAdSkill,
  optimiseAdsSkill,
  pauseAdSkill,
  updateBudgetSkill,
  schedulePostSkill,
  generateVideoSkill,
  manageLeadsSkill,
  manageAppointmentsSkill,
  manageOffersSkill,
  manageCustomerChatsSkill,
  type SkillId,
  type SkillModule,
  // Orchestrator (W-C03-B). Re-exported here so consumers of
  // `@borradh-workspace/features/assistant` (eval harness W-C04-A, controller
  // W-C03-D) don't need to reach into `./skills/`. Cross-boundary barrel
  // patch landed by W-C04-B; the symbols themselves are owned by W-C03-B.
  buildOrchestratorPrompt,
  buildPersonaBlock,
  buildSkillIndexBlock,
  buildSkillFragmentsBlock,
  buildBusinessContextBlock,
  type AnthropicSystemBlock,
  type OrchestratorPrompt,
  type OrchestratorOverrides,
} from './skills/index.js';

export {
  getAssistantUsage,
  type AssistantUsage,
  getAssistantUsageHistory,
  getUsageHistorySchema,
  type AssistantUsageHistory,
  type GetUsageHistoryInput,
  type UsageHistoryDay,
  type UsageHistoryMonth,
  type UsageHistoryTool,
  incrementAssistantUsage,
  getAssistantContext,
  type AssistantContext,
  listConversations,
  getConversation,
  // WS-10 — bounded most-recent-N message loader. The WhatsApp worker has no
  // client to resend the thread, so it rebuilds turn history from the DB.
  getConversationMessages,
  getConversationMessagesSchema,
  type GetConversationMessagesInput,
  type GetConversationMessagesResult,
  // Outbound delivery target resolver — paired phone + owner for a whatsapp
  // conversation, used by the proactive outbound worker.
  getWhatsappConversationTarget,
  getWhatsappConversationTargetSchema,
  type GetWhatsappConversationTargetInput,
  type WhatsappConversationTarget,
  createConversation,
  createConversationSchema,
  type CreateConversationInput,
  updateConversation,
  updateConversationSchema,
  type UpdateConversationInput,
  deleteConversation,
  saveMessages,
  saveMessagesSchema,
  type SaveMessagesInput,
  generateConversationTitle,
  generateTitleSchema,
  type GenerateTitleInput,
  escalateConversation,
  escalateConversationSchema,
  type EscalateConversationInput,
  requestClaireHandoff,
  requestClaireHandoffSchema,
  type RequestClaireHandoffInput,
  type RequestClaireHandoffServiceResult,
  createRecommendation,
  createRecommendationSchema,
  type CreateRecommendationInput,
  assistantPrimaryActionSchema,
  type AssistantPrimaryActionInput,
  listActiveRecommendations,
  listActiveRecommendationsSchema,
  type ListActiveRecommendationsInput,
  dismissRecommendation,
  dismissRecommendationSchema,
  type DismissRecommendationInput,
  markRecommendationActioned,
  markRecommendationActionedSchema,
  type MarkRecommendationActionedInput,
  findActiveRecommendationByKind,
  findActiveRecommendationByKindSchema,
  type FindActiveRecommendationByKindInput,
  generateRecommendationPayload,
  generateRecommendationPayloadSchema,
  type GenerateRecommendationPayloadInput,
  type GeneratedPayload,
  validateGeneratedCopy,
  getStaticFallback,
  createConfirmationToken,
  createConfirmationTokenSchema,
  type CreateConfirmationTokenInput,
  type CreatedConfirmationToken,
  verifyConfirmationToken,
  verifyConfirmationTokenSchema,
  type VerifyConfirmationTokenInput,
  type ConfirmationVerification,
  // Action-intent dedupe (Phase 4 — idempotency & duplicate protection)
  recordActionIntent,
  recordActionIntentSchema,
  type RecordActionIntentInput,
  type RecordActionIntentResult,
  findSimilarActionIntents,
  findSimilarActionIntentsSchema,
  type FindSimilarActionIntentsInput,
  type FindSimilarActionIntentsData,
  type FindSimilarActionIntentsResult,
  type SimilarActionIntentCandidate,
  findSimilarCampaigns,
  findSimilarLeadForms,
  normalizeActionKey,
  cleanupExpiredTokens,
  type CleanupExpiredTokensOutput,
  classifyIntent,
  classifyIntentSchema,
  clearClassifyIntentCache,
  type ClassifyIntentInput,
  type ClassifyIntentOutput,
  type ClassifyIntentResult,
  appendLoadedSkill,
  appendLoadedSkillSchema,
  type AppendLoadedSkillInput,
  type AppendLoadedSkillOutput,
  type AppendLoadedSkillResult,
  flagBudgetFailure,
  clearBudgetFailure,
  resolveBudgetFailureInterlock,
  budgetFailureInterlockSchema,
  resolveBudgetFailureInterlockSchema,
  type BudgetFailureInterlockInput,
  type ResolveBudgetFailureInterlockInput,
  type FlagBudgetFailureResult,
  type ResolveBudgetFailureInterlockResult,
  setInitialSkillState,
  setInitialSkillStateSchema,
  type SetInitialSkillStateInput,
  type SetInitialSkillStateOutput,
  type SetInitialSkillStateResult,
  signUploadUrl,
  signUploadUrlSchema,
  type SignUploadUrlInput,
  type SignUploadUrlOutput,
  type SignUploadUrlResult,
  type AssistantUploadMimeType,
  ASSISTANT_UPLOAD_MIME_TYPES,
  ASSISTANT_UPLOAD_MAX_BYTES,
  // C-13 populator wrappers (knowledge base ingestion). `writeKnowledgeEntry`
  // is the shared embed-then-insert path consumed by the 3 populator
  // services (conversation summaries, operational snapshots, remember tool).
  // `summariseConversation` is the post-conversation hook the chat
  // controller fires from `onFinish`; rate-limited to once per hour per
  // conversation in the service layer.
  writeKnowledgeEntry,
  writeKnowledgeEntrySchema,
  type WriteKnowledgeEntryInput,
  type WriteKnowledgeEntryOutput,
  type WriteKnowledgeEntryResult,
  summariseConversation,
  summariseConversationSchema,
  clearSummariseConversationRateLimit,
  type SummariseConversationInput,
  type SummariseConversationOutput,
  type SummariseConversationResult,
  buildOperationalSnapshot,
  buildOperationalSnapshotSchema,
  type BuildOperationalSnapshotInput,
  type BuildOperationalSnapshotOutput,
  type BuildOperationalSnapshotResult,
  runOperationalSnapshotCron,
  // W-C10-clip-tray Step 7 — polling-on-send draft-clips system block.
  // Lives in features/ per the project rule that DB queries don't run in
  // apps/api. The controller wraps it via apps/api/src/assistant/lib.
  buildDraftClipsSystemText,
  buildDraftClipsSystemTextSchema,
  type BuildDraftClipsSystemTextInput,
  type BuildDraftClipsSystemTextOutput,
  type BuildDraftClipsSystemTextResult,
  // C-14 memory primitives (settings UI surface for user-managed memories).
  // Three CRUD endpoints scoped to `type: 'preference'`; conversation
  // summaries + operational snapshots are not exposed here.
  listMemories,
  listMemoriesSchema,
  type ListMemoriesInput,
  type ListMemoriesItem,
  type ListMemoriesOutput,
  type ListMemoriesResult,
  editMemory,
  editMemorySchema,
  type EditMemoryInput,
  type EditMemoryOutput,
  type EditMemoryResult,
  deleteMemory,
  deleteMemorySchema,
  type DeleteMemoryInput,
  type DeleteMemoryOutput,
  type DeleteMemoryResult,
  // Content rules — the same memory store, narrowed to `metadata.domain =
  // 'content'` and org-wide scope, feeding every copy-generation prompt.
  // Deletion reuses `deleteMemory` above; there is no separate delete path.
  listContentRules,
  listContentRulesSchema,
  getContentRuleLines,
  MAX_CONTENT_RULES,
  type ContentRule,
  type ListContentRulesInput,
  type ListContentRulesOutput,
  type ListContentRulesResult,
  saveContentRule,
  saveContentRuleSchema,
  type SaveContentRuleInput,
  type SaveContentRuleOutput,
  type SaveContentRuleResult,
  // WS-3 — Owner WhatsApp pairing services. start → pending row + code;
  // verify → stamp sender E.164 + active (driven by the inbound webhook in
  // WS-10); resolveOwnerByPhone → active lookup by phone (webhook hot path);
  // revoke → null the phone so the number can re-pair; getWhatsappLinkStatus
  // → settings card read/poll.
  startWhatsappLink,
  startWhatsappLinkSchema,
  type StartWhatsappLinkInput,
  type StartWhatsappLinkOutput,
  verifyWhatsappLink,
  verifyWhatsappLinkSchema,
  type VerifyWhatsappLinkInput,
  type VerifyWhatsappLinkOutput,
  resolveOwnerByPhone,
  type ResolvedOwner,
  // WS-10 — the Claire inbound pipeline itself (pairing / STOP / owner-turn
  // routing). The WhatsApp webhook calls this and does nothing else.
  handleClaireWhatsappInbound,
  logClaireDecision,
  type ClaireInboundLogger,
  type HandleClaireWhatsappInboundInput,
  revokeWhatsappLink,
  revokeWhatsappLinkSchema,
  type RevokeWhatsappLinkInput,
  getWhatsappLinkStatus,
  getWhatsappLinkStatusSchema,
  type GetWhatsappLinkStatusInput,
  type WhatsappLinkStatus,
  // WS-8 — pending-confirmation helpers on the assistant conversation. The
  // WhatsApp preview tools (WS-6) call set/clear to record a single in-flight
  // destructive-action gate; the worker (WS-10) reads it via get to decide
  // whether an inbound affirmation satisfies the publish gate.
  setPendingConfirmation,
  setPendingConfirmationSchema,
  type SetPendingConfirmationInput,
  clearPendingConfirmation,
  clearPendingConfirmationSchema,
  type ClearPendingConfirmationInput,
  getPendingConfirmation,
  getPendingConfirmationSchema,
  type GetPendingConfirmationInput,
  type PendingConfirmation,
  type PendingConfirmationKind,
  // WS-10 — find-or-create the single persistent whatsapp Claire conversation
  // per (userId, org). The worker anchors every inbound owner message to it.
  findOrCreateWhatsappConversation,
  findOrCreateWhatsappConversationSchema,
  type FindOrCreateWhatsappConversationInput,
  type WhatsappConversation,
} from './services/index.js';

// WS-10 — Claire-on-WhatsApp inbound turn queue (BullMQ). The webhook enqueues
// a job; the worker (apps/api/src/chatbot-worker) consumes it.
export {
  CLAIRE_WHATSAPP_TURN_QUEUE,
  claireWhatsappTurnJobSchema,
  type ClaireWhatsappTurnJobPayload,
  queueClaireWhatsappTurn,
  getClaireWhatsappTurnQueue,
  closeClaireWhatsappTurnQueue,
  type QueueClaireWhatsappTurnResult,
} from './whatsapp-turn-queue/index.js';

// Proactive/async outbound delivery to a paired owner (generic transport for
// pushing polling-style results — finished renders, graphics, batches — that
// the web surfaces by client polling but WhatsApp can't see). Producers run
// wherever a job completes; the API chatbot-worker consumes + delivers.
export {
  CLAIRE_WHATSAPP_OUTBOUND_QUEUE,
  claireWhatsappOutboundJobSchema,
  claireOutboundMessageSchema,
  type ClaireWhatsappOutboundJobPayload,
  type ClaireOutboundMessage,
  queueClaireWhatsappOutbound,
  getClaireWhatsappOutboundQueue,
  closeClaireWhatsappOutboundQueue,
  type QueueClaireWhatsappOutboundResult,
} from './whatsapp-outbound/index.js';

// Eval-harness public surface. Re-exported here so the apps/api-side
// live-controller adapter (W-C04-A-finish) can import the harness types
// without a per-subpath package export. Dev-only consumers; production
// callers ignore these.
export {
  loadFixtureModules,
  compareFixture,
} from './eval/runner.js';
export type {
  ClaireFixture,
  EvalMode,
  FixtureCategory,
  FixtureExpectation,
  FixtureModule,
  FixtureOutcome,
  HarnessHardBlockCheck,
  HarnessPresentation,
  HarnessRecording,
  HarnessToolCall,
  HarnessToolResult,
  HarnessToolStub,
  HarnessTrace,
  HarnessTurnTrace,
  RunSummary,
} from './eval/index.js';

export {
  runContentNoPost14DaysTrigger,
  runContentUnusedAssetsTrigger,
  runContentLearningPhasePromptTrigger,
  runLeadUnreplied2hTrigger,
  runPreAppointmentPrepTrigger,
  runCampaignLearningPhaseExitTrigger,
  runLearningPhaseReassuranceTrigger,
  runPromptCreateFirstAdTrigger,
  runPromptCreateFirstOfferTrigger,
  runPromptRecordFirstVideoTrigger,
  runPromptCreateFirstPostTrigger,
  // Phase 4 — Lifecycle recommendation triggers (W-C16-lifecycle-triggers).
  runNoShowSurgeTrigger,
  runOfferExpiringSoonTrigger,
  // Phase 4 — Performance recommendation triggers (W-C16-perf-triggers).
  runCplSpikeTrigger,
  runCreativeBurnoutTrigger,
  runLeadVolumeDropTrigger,
  // PRD-1 — Campaign Troubleshooting Framework (proactive trigger).
  runFourDayNoLeadsTrigger,
} from './triggers/index.js';

// WS-11 — Claire-on-WhatsApp proactive nudges (templates + gating + bridge +
// scheduler runner). Behind CLAIRE_WHATSAPP_PROACTIVE_ENABLED; templates are
// operator-approved in the Meta UI (plan §0.C).
export {
  CLAIRE_NUDGE_TEMPLATES,
  CLAIRE_NUDGE_TEMPLATE_LANGUAGE,
  submitClaireNudgeTemplates,
  type ClaireNudgeTemplateName,
  type ClaireNudgeTemplateDef,
  type SubmitClaireNudgeTemplatesResult,
  DEFAULT_NUDGE_POLICY,
  decideNudge,
  isWithinQuietHours,
  type NudgeCandidate,
  type NudgeDecision,
  type NudgeOwnerSignals,
  type NudgePolicy,
  type NudgeSkipReason,
  isOptedOut,
  parseOptOutPhones,
  type NudgeOptOutConfig,
  sendClaireNudge,
  renderTemplateBody,
  type SendClaireNudgeInput,
  type SendClaireNudgeResult,
  runClaireWhatsappNudges,
  defaultResolveCandidate,
  type NudgeRunOutcome,
  type RunNudgesDeps,
} from './proactive-nudges/index.js';
