/**
 * Sequence-specific error codes
 */
export const SequenceErrorCodes = {
  SEQUENCE_NOT_FOUND: 'SEQUENCE_NOT_FOUND',
  SEQUENCE_ALREADY_ACTIVE: 'SEQUENCE_ALREADY_ACTIVE',
  SEQUENCE_ALREADY_INACTIVE: 'SEQUENCE_ALREADY_INACTIVE',
  INVALID_SEQUENCE_STRUCTURE: 'INVALID_SEQUENCE_STRUCTURE',
  STEP_NOT_FOUND: 'STEP_NOT_FOUND',
  INSUFFICIENT_CREDITS_TO_PUBLISH: 'INSUFFICIENT_CREDITS_TO_PUBLISH',
  MISSING_INTEGRATIONS: 'MISSING_INTEGRATIONS',
} as const;

export type SequenceErrorCode =
  (typeof SequenceErrorCodes)[keyof typeof SequenceErrorCodes];
