/**
 * GATE 3 — the undeclared-policy burn-down.
 *
 * Every entry point (controller route, Claire tool) must DECLARE who may
 * invoke it. The ids below are the ones that declare nothing today.
 *
 * A route declares policy through the guards in scope, or by being explicitly
 * marked public. A tool declares it through `ToolDefinition.policy`. Note that
 * `destructive` is NOT a policy: it is a human-in-the-loop confirmation gate
 * ("ask before doing this"), not an authorization one ("this caller may not do
 * this at all").
 *
 * THIS LIST ONLY SHRINKS. A new undeclared entry point fails the gate.
 * See `entry-point-policy.spec.ts` for the regeneration command.
 *
 * The doc's rule is "do not move policy anywhere before Gate 3 exists". This
 * is that gate. Nothing enforces `policy` at runtime yet, on purpose — the
 * declaration has to be countable before the enforcement can be moved.
 */
export const UNDECLARED_POLICY_BASELINE: ReadonlySet<string> = new Set([
  'GET /',
  'GET /auth/google',
  'GET /auth/google/sign-up',
  'GET /auth/session',
  'GET /auth/verify-email',
  'GET /c/u/:token',
  'GET /health',
  'GET /health/live',
  'GET /health/ready',
  'GET /integrations/facebook/webhook',
  'GET /mobile-status/:videoId',
  'GET /public/booking/:organizationSlug',
  'GET /public/booking/:organizationSlug/manage/:token',
  'GET /public/booking/:organizationSlug/slots',
  'GET /public/intake/:organizationSlug/:token',
  'GET /public/venue/:organizationSlug',
  'GET /public/venue/:organizationSlug/:locationSlug',
  'GET /webhooks/meta/leadgen',
  'GET /webhooks/meta/messaging',
  'GET /webhooks/whatsapp',
  'POST /auth/apple/native',
  'POST /auth/change-email',
  'POST /auth/change-password',
  'POST /auth/forgot-password',
  'POST /auth/resend-verification',
  'POST /auth/reset-password',
  'POST /auth/sign-in',
  'POST /auth/sign-out',
  'POST /auth/sign-up',
  'POST /auth/two-factor/enable',
  'POST /auth/two-factor/verify-totp',
  'POST /auth/verify-email',
  'POST /c/u/:token',
  'POST /integrations/facebook/webhook',
  'POST /mobile-token',
  'POST /multipart/complete',
  'POST /multipart/initiate',
  'POST /multipart/sign-parts',
  'POST /presigned-download-url',
  'POST /presigned-url',
  'POST /public/booking/:organizationSlug/manage/:token/cancel',
  'POST /public/booking/:organizationSlug/manage/:token/reschedule',
  'POST /public/booking/:organizationSlug/submit',
  'POST /public/intake/:organizationSlug/:token/submit',
  'POST /webhooks/meta/data-deletion',
  'POST /webhooks/stripe-connect',
  'appointments_bookAppointment',
  'appointments_cancelAppointment',
  'appointments_findOpenSlots',
  'appointments_listAppointments',
  'appointments_markNoShow',
  'appointments_rescheduleAppointment',
  'appointments_setAppointmentStatus',
  'appointments_summariseUpcomingDay',
  'campaigns_checkChannels',
  'campaigns_create',
  'campaigns_createSegment',
  'campaigns_launch',
  'campaigns_list',
  'campaigns_listWhatsappTemplates',
  'campaigns_previewAudience',
  'campaigns_segments_list',
  'campaigns_setMessage',
  'campaigns_showCampaignPreview',
  'claire_getAlternativeRecommendation',
  'claire_publishAd',
  'claire_publishOffer',
  'claire_recommendOfferForService',
  'claire_recommendServiceForAds',
  'claire_resolveDisagreement',
  'claire_saveAdDraft',
  'claire_saveOfferDraft',
  'claire_setPendingAdBudget',
  'claire_setPendingAdCaption',
  'claire_setPendingAdCopy',
  'claire_setPendingAdCreative',
  'claire_setPendingAdHeadline',
  'claire_setPendingAdPrice',
  'claire_setPendingAdSchedule',
  'claire_setPendingAdService',
  'claire_setPendingAdTargeting',
  'claire_setPendingOfferCode',
  'claire_setPendingOfferIntroPrice',
  'claire_setPendingOfferLocations',
  'claire_setPendingOfferName',
  'claire_setPendingOfferRedemptionRules',
  'claire_setPendingOfferService',
  'claire_setPendingOfferValidity',
  'claire_showAdPreview',
  'claire_showOfferPreview',
  'context_checkConnectedPages',
  'context_createService',
  'context_deleteService',
  'context_getOrganizationContext',
  'context_getServiceDetails',
  'context_listOffers',
  'context_listRecentGraphics',
  'context_listRecentVideos',
  'context_listServices',
  'context_updateService',
  'customer-conversations_confirmAssignConversation',
  'customer-conversations_confirmEscalateToHuman',
  'customer-conversations_draftReply',
  'customer-conversations_listOpenConversations',
  'customer-conversations_sendReply',
  'customer-conversations_summariseConversation',
  'customer-conversations_summariseConversationsThisWeek',
  'lead-forms_createLeadForm',
  'lead-forms_listLeadForms',
  'lead-forms_previewLeadForm',
  'lead-forms_updateLeadForm',
  'leads_createLead',
  'leads_getLeadStats',
  'leads_listLeads',
  'leads_searchLeads',
  'leads_summariseRecentLeads',
  'leads_updateLead',
  'meta-ads_checkMetaIntegration',
  'meta-ads_confirmLaunchAd',
  'meta-ads_confirmPauseAd',
  'meta-ads_createCampaign',
  'meta-ads_createDraftAd',
  'meta-ads_deleteDraftAd',
  'meta-ads_diagnoseCampaign',
  'meta-ads_duplicateAd',
  'meta-ads_duplicateCampaign',
  'meta-ads_executeLaunchAd',
  'meta-ads_executePauseAd',
  'meta-ads_generateAdCopy',
  'meta-ads_getAdInsights',
  'meta-ads_getCampaignInsights',
  'meta-ads_listCampaigns',
  'meta-ads_listRecentAds',
  'meta-ads_previewCampaign',
  'meta-ads_replaceAdCreative',
  'meta-ads_suggestAdOptimizations',
  'meta-ads_updateAd',
  'meta_dispatchTour',
  'meta_loadSkill',
  'meta_remember',
  'offers_createOffer',
  'offers_expireOffer',
  'offers_extendOffer',
  'offers_getOfferPerformance',
  'offers_suggestIntroOffer',
  'org-defaults_setOrgDefault',
  'social-posts_createSocialPostDraft',
  'social-posts_deleteSocialPostDraft',
  'social-posts_generatePostCaption',
  'social-posts_listRecentPosts',
  'social-posts_publishPostNow',
  'social-posts_schedulePost',
  'social-posts_suggestPostingTime',
  'social-posts_updateSocialPostDraft',
  'support_requestSupportChat',
  'videos_autoSelectClips',
  'videos_autoSelectMusic',
  'videos_deleteDraftVideo',
  'videos_generateTalkingHeadQR',
  'videos_generateVideoScript',
  'videos_getVideoStatus',
  'videos_listDraftClips',
]);
