import {
  isForeignKeyViolation,
  voiceEmbedding,
} from '@borradh-workspace/database';
import {
  createLogger,
  logError,
  trackedResult,
} from '@borradh-workspace/observability';
import { generateEmbeddings } from '../../../assistant/knowledge/embed.js';
import {
  type DbConnection,
  ErrorCodes,
  FeatureError,
  type Result,
  err,
  ok,
} from '../../../shared/index.js';
import {
  type EmbedVoiceExamplesInput,
  embedVoiceExamplesSchema,
} from './embed-voice-examples.schema.js';

const logger = createLogger('EmbedVoiceExamples');

const BATCH_SIZE = 100;

const embedVoiceExamplesImpl = async (
  db: DbConnection,
  input: EmbedVoiceExamplesInput
): Promise<Result<{ embeddedCount: number }>> => {
  const parsed = embedVoiceExamplesSchema.safeParse(input);
  if (!parsed.success) {
    return err(
      new FeatureError(ErrorCodes.VALIDATION_ERROR, 'Invalid input', {
        issues: parsed.error.issues,
      })
    );
  }

  const { organizationId, metaAdsPageId, messagePairs } = parsed.data;

  if (messagePairs.length === 0) {
    return ok({ embeddedCount: 0 });
  }

  let totalEmbedded = 0;

  try {
    // Process in batches of BATCH_SIZE
    for (let i = 0; i < messagePairs.length; i += BATCH_SIZE) {
      const batch = messagePairs.slice(i, i + BATCH_SIZE);

      // Embed the customerMessage texts (NOT the replies)
      const texts = batch.map((pair) => pair.customerMessage);
      const embeddings = await generateEmbeddings(texts);

      // Build insert values (id is auto-generated by $defaultFn in schema)
      const values = batch.map((pair, idx) => ({
        organizationId,
        metaAdsPageId,
        customerMessage: pair.customerMessage,
        businessReply: pair.businessReply,
        embedding: embeddings[idx],
        messageTimestamp: pair.timestamp ?? null,
        metadata: pair.conversationId
          ? { conversationId: pair.conversationId }
          : null,
      }));

      await db.insert(voiceEmbedding).values(values);
      totalEmbedded += values.length;

      logger.info('Embedded voice examples batch', {
        organizationId,
        batchIndex: Math.floor(i / BATCH_SIZE),
        batchSize: values.length,
        totalSoFar: totalEmbedded,
      });
    }

    return ok({ embeddedCount: totalEmbedded });
  } catch (error) {
    // The Page (or org) this batch points at was deleted concurrently —
    // report as a validation problem with the caller's input, not a 500.
    // drizzle wraps the postgres.js error — the constraint lives on the
    // `.cause` chain, not `error.message` (see isForeignKeyViolation).
    if (
      isForeignKeyViolation(
        error,
        'voice_embedding_meta_ads_page_id_meta_ads_page_id_fk'
      )
    ) {
      return err(
        new FeatureError(
          ErrorCodes.VALIDATION_ERROR,
          'The Meta Ads Page for this voice example no longer exists'
        )
      );
    }
    if (
      isForeignKeyViolation(
        error,
        'voice_embedding_organization_id_organization_id_fk'
      )
    ) {
      return err(
        new FeatureError(
          ErrorCodes.VALIDATION_ERROR,
          'The organization for this voice example no longer exists'
        )
      );
    }

    logError('voiceCloning.embedVoiceExamples', error, {
      feature: 'voice-cloning',
      extra: { organizationId, metaAdsPageId, totalEmbedded },
    });
    return err(
      new FeatureError(
        ErrorCodes.INTERNAL_ERROR,
        'Failed to embed voice examples'
      )
    );
  }
};

export const embedVoiceExamples = (
  db: DbConnection,
  input: EmbedVoiceExamplesInput
) =>
  trackedResult(
    'voiceCloning.embedVoiceExamples',
    () => embedVoiceExamplesImpl(db, input),
    {
      properties: {
        organizationId: input.organizationId,
        metaAdsPageId: input.metaAdsPageId,
        pairCount: input.messagePairs.length,
      },
    }
  );

export type EmbedVoiceExamplesResult = Awaited<
  ReturnType<typeof embedVoiceExamples>
>;
