import { randomUUID } from 'node:crypto';
/**
 * CAPABILITY suite for footage selection — `claimRotatedAsset`.
 *
 * WHY THIS RUNS AGAINST REAL POSTGRES
 * -----------------------------------
 * The rules under test are expressed entirely in ONE SQL statement: the LRU
 * ordering, the own-before-stock tie-break, and the quality floor all live in
 * an `UPDATE ... WHERE id = (SELECT ... ORDER BY ... FOR UPDATE SKIP LOCKED)`.
 * A mocked `db` can only assert that the statement was issued, which is exactly
 * the assertion that stays green while the ordering is wrong. So these run
 * against the testcontainers Postgres and read back what was actually claimed.
 *
 * WHAT IT PINS
 * ------------
 * The owner stated the rule as two cases:
 *
 *   - one GOOD own clip  → own footage first, stock on the SECOND ask
 *   - one BAD own clip   → stock from the start
 *
 * Both are meant to fall out of a single least-recently-used claim over a pool
 * containing own AND stock, with own winning only a tie. Nothing here special-
 * cases either scenario, which is the point: if the tie-break or the floor is
 * removed, these fail rather than a customer reporting the same clip in every
 * video weeks later.
 */
import {
  type AssetSource,
  type AssetType,
  asset,
  assetAnalysis,
  assetService,
  db,
} from '@borradh-workspace/database';
import { claimRotatedAsset } from '@borradh-workspace/features/assets';
import { and, eq } from 'drizzle-orm';
import { seedOrgWithMember, seedService } from './harness.js';

/**
 * Insert an asset and link it to a service, i.e. put it in the rotation pool.
 * `source` is what distinguishes the org's own upload from minted stock.
 */
async function seedPoolAsset(input: {
  organizationId: string;
  serviceId: string;
  userId: string;
  source: AssetSource;
  type?: AssetType;
  transcodeStatus?: 'ready' | 'pending' | 'failed' | 'skipped';
  qualityScore?: number;
  qualityFlags?: Record<string, boolean>;
  lastUsedAt?: Date | null;
}): Promise<string> {
  const id = `ast_${randomUUID()}`;
  await db.insert(asset).values({
    id,
    name: `asset-${id}`,
    blobUrl: `https://example.test/${id}.mp4`,
    type: input.type ?? 'video',
    source: input.source,
    transcodeStatus: input.transcodeStatus ?? 'ready',
    organizationId: input.organizationId,
    uploadedById: input.userId,
  });

  if (input.qualityScore !== undefined || input.qualityFlags) {
    await db.insert(assetAnalysis).values({
      id: `ana_${randomUUID()}`,
      assetId: id,
      organizationId: input.organizationId,
      analysisResult: {
        ...(input.qualityScore !== undefined
          ? { qualityScore: input.qualityScore }
          : {}),
        ...(input.qualityFlags ? { qualityFlags: input.qualityFlags } : {}),
      },
    });
  }

  await db.insert(assetService).values({
    assetId: id,
    serviceId: input.serviceId,
    isAutoGenerated: true,
    lastUsedAt: input.lastUsedAt ?? null,
  });

  return id;
}

async function claim(organizationId: string, serviceId: string) {
  const result = await claimRotatedAsset(db, {
    organizationId,
    serviceId,
    requireThumbnail: false,
    mediaType: 'video',
    requireTranscodeReady: true,
  });
  if (!result.success) throw new Error('claim failed');
  return result.data;
}

describe('footage rotation — own and stock in ONE pool', () => {
  let organizationId: string;
  let userId: string;
  let serviceId: string;

  beforeEach(async () => {
    const seeded = await seedOrgWithMember('owner');
    organizationId = seeded.organizationId;
    userId = seeded.userId;
    serviceId = await seedService({ organizationId });
  });

  describe("the owner's rule: one GOOD own clip", () => {
    it('opens on the OWN clip first, then STOCK on the second ask', async () => {
      const own = await seedPoolAsset({
        organizationId,
        serviceId,
        userId,
        source: 'raw',
      });
      const stock = await seedPoolAsset({
        organizationId,
        serviceId,
        userId,
        source: 'stock',
      });

      // Both are never-used, so this is a pure tie — own wins it.
      const first = await claim(organizationId, serviceId);
      expect(first.assetId).toBe(own);

      // The own clip now carries a `last_used_at` and the stock clip does not.
      // NULLS FIRST does the rest; nothing special-cases "second ask".
      const second = await claim(organizationId, serviceId);
      expect(second.assetId).toBe(stock);
    });

    it('wraps back to the own clip once stock has been used too', async () => {
      const own = await seedPoolAsset({
        organizationId,
        serviceId,
        userId,
        source: 'raw',
      });
      await seedPoolAsset({
        organizationId,
        serviceId,
        userId,
        source: 'stock',
      });

      await claim(organizationId, serviceId);
      await claim(organizationId, serviceId);

      // Least-recently-used is now the own clip again.
      const third = await claim(organizationId, serviceId);
      expect(third.assetId).toBe(own);
    });
  });

  describe("the owner's rule: one BAD own clip", () => {
    it('goes to STOCK from the start when the own clip is below the floor', async () => {
      await seedPoolAsset({
        organizationId,
        serviceId,
        userId,
        source: 'raw',
        qualityScore: 0.1,
      });
      const stock = await seedPoolAsset({
        organizationId,
        serviceId,
        userId,
        source: 'stock',
      });

      const first = await claim(organizationId, serviceId);
      expect(first.assetId).toBe(stock);
    });

    it('excludes a shaky own clip even when its score is fine', async () => {
      await seedPoolAsset({
        organizationId,
        serviceId,
        userId,
        source: 'raw',
        qualityScore: 0.9,
        qualityFlags: { isShaky: true },
      });
      const stock = await seedPoolAsset({
        organizationId,
        serviceId,
        userId,
        source: 'stock',
      });

      const first = await claim(organizationId, serviceId);
      expect(first.assetId).toBe(stock);
      // The service HAS media; the floor is why it wasn't used. That
      // distinction is the difference between "upload something" and "upload
      // something BETTER" as advice to the owner.
      expect(first.excludedForQuality).toBe(1);
    });

    it('keeps an UNANALYSED own clip eligible — no score is not a bad score', async () => {
      const own = await seedPoolAsset({
        organizationId,
        serviceId,
        userId,
        source: 'raw',
      });
      await seedPoolAsset({
        organizationId,
        serviceId,
        userId,
        source: 'stock',
      });

      const first = await claim(organizationId, serviceId);
      expect(first.assetId).toBe(own);
    });
  });

  describe('gates that keep selection in lock-step with the render', () => {
    it('skips a still-transcoding clip rather than seeding an un-renderable video', async () => {
      await seedPoolAsset({
        organizationId,
        serviceId,
        userId,
        source: 'raw',
        transcodeStatus: 'pending',
      });
      const stock = await seedPoolAsset({
        organizationId,
        serviceId,
        userId,
        source: 'stock',
      });

      const first = await claim(organizationId, serviceId);
      expect(first.assetId).toBe(stock);
    });

    it('will not fill a clip slot with a still', async () => {
      await seedPoolAsset({
        organizationId,
        serviceId,
        userId,
        source: 'raw',
        type: 'image',
      });

      const first = await claim(organizationId, serviceId);
      expect(first.assetId).toBeNull();
    });

    it('reports an empty pool rather than inventing a claim', async () => {
      const first = await claim(organizationId, serviceId);
      expect(first.assetId).toBeNull();
      expect(first.poolSize).toBe(0);
    });
  });

  describe('rotation memory', () => {
    it('stamps use_count as it claims, in the same statement', async () => {
      const own = await seedPoolAsset({
        organizationId,
        serviceId,
        userId,
        source: 'raw',
      });

      const first = await claim(organizationId, serviceId);
      expect(first.assetId).toBe(own);
      expect(first.previousUseCount).toBe(0);

      const [link] = await db
        .select({ useCount: assetService.useCount })
        .from(assetService)
        .where(
          and(
            eq(assetService.assetId, own),
            eq(assetService.serviceId, serviceId)
          )
        );
      expect(link?.useCount).toBe(1);
    });

    it('counts own AND stock in the pool size it reports', async () => {
      await seedPoolAsset({
        organizationId,
        serviceId,
        userId,
        source: 'raw',
      });
      await seedPoolAsset({
        organizationId,
        serviceId,
        userId,
        source: 'stock',
      });

      // The number that answers "how much variety does this service have?".
      // Before stock joined the pool it could only ever count own uploads,
      // which is why a service reading `poolSize: 1` looked unfixable.
      const first = await claim(organizationId, serviceId);
      expect(first.poolSize).toBe(2);
    });
  });
});
