/**
 * Per-turn "active context" hint for Claire.
 *
 * When the user navigates to `/assistant` from a feature page (W-C18 cross-app
 * entry points — e.g. the `<AskClaireButton>` on a lead detail dialog), the
 * URL carries `entityType` + `entityId` query params. The frontend forwards
 * those on the **first** chat send only; the controller injects a small
 * sentence into the system prompt for that turn so the model knows what the
 * user is currently looking at.
 *
 * Subsequent turns don't re-inject — the natural conversation history keeps
 * the entity in context.
 *
 * The controller does NOT fetch the entity here. That belongs to the model's
 * tools (which enforce per-tool RBAC). This module only emits the reference,
 * not the data.
 */

const ALLOWED_ENTITY_TYPES = [
  'lead',
  'appointment',
  'ad',
  'meta_campaign',
  'offer',
  'conversation',
  // A post in the bulk-content queue. The review page runs the ordinary
  // assistant chat, so the post under discussion arrives the same way every
  // other entity does rather than through a bespoke turn handler.
  'content_item',
] as const;

export type ActiveContextEntityType = (typeof ALLOWED_ENTITY_TYPES)[number];

/** Bound entityId length so a malformed URL can't bloat the system prompt. */
const ENTITY_ID_MAX_LENGTH = 128;

/**
 * Allowed charset for `entityId`. Restrict to alphanumerics + `_-` so a
 * shareable link can't smuggle prompt-injection text into the system prompt
 * via the active-context hint. All entity IDs the rest of the app uses
 * (cuid2, uuid, drizzle text PKs) fit this charset.
 */
const ENTITY_ID_PATTERN = /^[a-zA-Z0-9_-]+$/;

interface ActiveContextInput {
  entityType?: unknown;
  entityId?: unknown;
}

/**
 * Validates and normalises the active-context input from the chat body.
 * Returns `null` for missing or malformed input — the caller should treat
 * `null` as "no context to inject" rather than as an error (a stale URL or
 * future-version entity type shouldn't break the chat).
 */
export function parseActiveContext(
  input: ActiveContextInput
): { entityType: ActiveContextEntityType; entityId: string } | null {
  const { entityType, entityId } = input;
  if (typeof entityType !== 'string' || typeof entityId !== 'string') {
    return null;
  }
  if (!ALLOWED_ENTITY_TYPES.includes(entityType as ActiveContextEntityType)) {
    return null;
  }
  const trimmedId = entityId.trim();
  if (!trimmedId || trimmedId.length > ENTITY_ID_MAX_LENGTH) {
    return null;
  }
  if (!ENTITY_ID_PATTERN.test(trimmedId)) {
    // Anything outside `[a-zA-Z0-9_-]` is rejected so a shareable URL with
    // a victim-facing payload can't seed a prompt-injection sentence into
    // the system prompt.
    return null;
  }
  return {
    entityType: entityType as ActiveContextEntityType,
    entityId: trimmedId,
  };
}

/**
 * Builds the per-turn system-prompt sentence describing the active entity.
 * Kept short so it doesn't fight the orchestrator's own framing.
 */
export function buildActiveContextSystemText(
  entityType: ActiveContextEntityType,
  entityId: string
): string {
  return `Active context: the user is currently viewing ${entityType} ${entityId}. Use this context if relevant.`;
}

/**
 * The same sentence, plus what the item actually CONTAINS.
 *
 * An ordinary chat works because the ids are already in the transcript: Claire
 * made the video, so she still has its id when asked to change it. A queued
 * post has no such history — it was generated by the monthly cron, in another
 * conversation, and the review chat starts empty. Naming only the ITEM left her
 * holding an id that no editing tool accepts, so she asked the owner which post
 * they meant while they were looking at it.
 *
 * Naming the asset here puts her in the same position she is in after creating
 * something, which is why the editing tools then work unchanged.
 */
export function buildContentItemContextSystemText(input: {
  itemId: string;
  kind: 'video' | 'graphic';
  assetId: string | null;
  caption: string | null;
  reviewStatus: string;
  /** The words ON the video, field by field. Empty for graphics. */
  textFields?: Record<string, string | string[]>;
  templateKey?: string | null;
}): string {
  // Labelled, because there are now TWO ids in this sentence and the tools do
  // not accept them interchangeably. Handed "content item X … its graphic Y",
  // a model will pass Y to a tool that wants X and get a NOT_FOUND it then has
  // to explain.
  const asset = input.assetId
    ? `The ${input.kind} inside it has ${input.kind}Id="${input.assetId}" — that one is for editing the CONTENT.`
    : `It has no ${input.kind} yet.`;
  // Truncated: the caption is the owner's copy and can run long, and this line
  // is prepended to every turn.
  const caption = input.caption
    ? ` Its caption reads: "${input.caption.slice(0, 300)}".`
    : '';
  // The on-screen copy, numbered where it is a list.
  //
  // This is what makes "change point 3" answerable. In an ordinary chat the
  // copy arrives in the transcript — `createDraftVideo` returns its
  // `textFrames` — so Claire can read back what she made. A queued post has no
  // such turn, and without this she could only ask the owner what point 3 said
  // while they were looking at it.
  const entries = Object.entries(input.textFields ?? {});
  const listed = entries
    .map(([field, value]) =>
      Array.isArray(value)
        ? `${field} = [${value.map((v, i) => `${i + 1}. "${v}"`).join(', ')}]`
        : `${field} = "${value}"`
    )
    .join('; ');
  const onScreen = entries.length
    ? ` The words on it, in the "${input.templateKey}" block — to change any of them, call patchContent with the owner's request in their own words: ${listed}.`
    : '';

  const rule =
    ' Use these ids directly — never ask which post they mean, and never ask' +
    ' what a numbered point says when it is listed above.';

  return (
    `Active context: the user is looking at a queued ${input.kind} post, ` +
    `review status ${input.reviewStatus}. ` +
    `itemId="${input.itemId}" — that one is for the POST (its caption, ` +
    `regenerating it, deciding on it). ${asset}${caption}${onScreen}${rule}`
  );
}
