import {
  assetAnalysis,
  assetService,
  organizationService,
  withOrgScope,
} from '@borradh-workspace/database';
import { trackedResult } from '@borradh-workspace/observability';
import { eq } from 'drizzle-orm';
import {
  type DbConnection,
  ErrorCodes,
  FeatureError,
  type Result,
  err,
  ok,
} from '../../../shared/index.js';
import {
  type GetAssetAnalysisInput,
  getAssetAnalysisSchema,
} from './get-asset-analysis.schema.js';

/**
 * Get asset analysis response type
 */
export interface GetAssetAnalysisResponse {
  analysis: typeof assetAnalysis.$inferSelect | null;
  linkedServices: Array<{
    id: string;
    serviceId: string;
    serviceName: string;
    serviceCategory: string;
    confidence: number | null;
    isAutoGenerated: boolean;
  }>;
}

/**
 * Internal implementation of get asset analysis
 */
const getAssetAnalysisImpl = async (
  db: DbConnection,
  input: GetAssetAnalysisInput
): Promise<Result<GetAssetAnalysisResponse>> => {
  // Validate input
  const parsed = getAssetAnalysisSchema.safeParse(input);
  if (!parsed.success) {
    return err(
      new FeatureError(ErrorCodes.VALIDATION_ERROR, 'Invalid input', {
        issues: parsed.error.issues,
      })
    );
  }

  const { assetId, organizationId } = parsed.data;

  return withOrgScope(
    async (tx) => {
      // Verify asset exists and belongs to the organization
      const existingAsset = await tx.query.asset.findFirst({
        where: (a, { eq, and, isNull }) =>
          and(
            eq(a.id, assetId),
            eq(a.organizationId, organizationId),
            isNull(a.deletedAt)
          ),
      });

      if (!existingAsset) {
        return err(
          new FeatureError(ErrorCodes.NOT_FOUND, 'Asset not found', { assetId })
        );
      }

      // Get the analysis record
      const analysis = await tx.query.assetAnalysis.findFirst({
        where: eq(assetAnalysis.assetId, assetId),
      });

      // Get linked services with their details
      const linkedServicesRaw = await tx
        .select({
          id: assetService.id,
          serviceId: assetService.serviceId,
          serviceName: organizationService.name,
          serviceCategory: organizationService.category,
          confidence: assetService.confidence,
          isAutoGenerated: assetService.isAutoGenerated,
        })
        .from(assetService)
        .innerJoin(
          organizationService,
          eq(assetService.serviceId, organizationService.id)
        )
        .where(eq(assetService.assetId, assetId));

      return ok({
        analysis: analysis ?? null,
        linkedServices: linkedServicesRaw,
      });
    },
    { db }
  );
};

/**
 * Get asset analysis results and linked services
 *
 * @param db - Database connection
 * @param input - Get asset analysis input
 * @returns Result with analysis data or error
 */
export const getAssetAnalysis = (
  db: DbConnection,
  input: GetAssetAnalysisInput
) =>
  trackedResult(
    'assets.getAssetAnalysis',
    () => getAssetAnalysisImpl(db, input),
    {
      properties: {
        assetId: input.assetId,
        organizationId: input.organizationId,
      },
      internalErrorsOnly: true,
    }
  );

/**
 * Result type for getAssetAnalysis
 */
export type GetAssetAnalysisResult = Awaited<
  ReturnType<typeof getAssetAnalysis>
>;
