import {
  beforeEach,
  createMockDatabase,
  describe,
  expect,
  expectResult,
  it,
  vi,
} from '@borradh-workspace/testing';
import { ErrorCodes } from '../../../shared/index.js';
import { getAssetAnalysis } from './get-asset-analysis.service.js';

describe('getAssetAnalysis', () => {
  const mockDb = createMockDatabase();

  beforeEach(() => {
    vi.clearAllMocks();
    mockDb._resetMocks();
  });

  const validInput = {
    assetId: 'asset_123',
    organizationId: 'org_123',
  };

  it('should return analysis and linked services when asset found', async () => {
    const mockAsset = {
      id: 'asset_123',
      name: 'Test Video',
      organizationId: 'org_123',
      type: 'video',
    };

    const mockAnalysis = {
      id: 'analysis_123',
      assetId: 'asset_123',
      status: 'completed',
      result: { tags: ['marketing'] },
      createdAt: new Date(),
    };

    const mockLinkedServices = [
      {
        id: 'link_1',
        serviceId: 'svc_1',
        serviceName: 'Haircut',
        serviceCategory: 'hair',
        confidence: 0.95,
        isAutoGenerated: true,
      },
    ];

    // Step 1: asset exists check
    mockDb.query.asset.findFirst.mockResolvedValueOnce(mockAsset);
    // Step 2: get analysis record
    mockDb.query.assetAnalysis.findFirst.mockResolvedValueOnce(mockAnalysis);
    // Step 3: get linked services (select chain ends with where)
    mockDb.where.mockResolvedValueOnce(mockLinkedServices);

    const result = await getAssetAnalysis(mockDb as never, validInput);

    expect(result.success).toBe(true);
    if (result.success) {
      expect(result.data.analysis).toBeDefined();
      expect(result.data.analysis?.status).toBe('completed');
      expect(result.data.linkedServices).toHaveLength(1);
      expect(result.data.linkedServices[0].serviceName).toBe('Haircut');
      expect(result.data.linkedServices[0].confidence).toBe(0.95);
    }
  });

  it('should return NOT_FOUND when asset does not exist', async () => {
    mockDb.query.asset.findFirst.mockResolvedValueOnce(null);

    await expectResult(
      getAssetAnalysis(mockDb as never, validInput)
    ).toFailWithCode(ErrorCodes.NOT_FOUND);
  });

  it('should return null analysis when no analysis exists', async () => {
    const mockAsset = {
      id: 'asset_123',
      name: 'Test Video',
      organizationId: 'org_123',
      type: 'video',
    };

    // Step 1: asset exists
    mockDb.query.asset.findFirst.mockResolvedValueOnce(mockAsset);
    // Step 2: no analysis
    mockDb.query.assetAnalysis.findFirst.mockResolvedValueOnce(null);
    // Step 3: no linked services
    mockDb.where.mockResolvedValueOnce([]);

    const result = await getAssetAnalysis(mockDb as never, validInput);

    expect(result.success).toBe(true);
    if (result.success) {
      expect(result.data.analysis).toBeNull();
      expect(result.data.linkedServices).toEqual([]);
    }
  });

  it('should return VALIDATION_ERROR for empty assetId', async () => {
    const invalidInput = {
      assetId: '',
      organizationId: 'org_123',
    };

    await expectResult(
      getAssetAnalysis(mockDb as never, invalidInput)
    ).toFailWithCode(ErrorCodes.VALIDATION_ERROR);

    expect(mockDb.query.asset.findFirst).not.toHaveBeenCalled();
  });

  it('should return VALIDATION_ERROR for empty organizationId', async () => {
    const invalidInput = {
      assetId: 'asset_123',
      organizationId: '',
    };

    await expectResult(
      getAssetAnalysis(mockDb as never, invalidInput)
    ).toFailWithCode(ErrorCodes.VALIDATION_ERROR);

    expect(mockDb.query.asset.findFirst).not.toHaveBeenCalled();
  });
});
